# Generated by Django 4.1 on 2022-08-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_giftoption1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonoptions',
            name='imagelink',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='amazonoptions',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
